import pytest


def test_foo():
    with pytest.raises(AssertionError) as e:
        pass
